### ISSUE TITLE
from-pg-value for custom ENUM type?

### ISSUE THREAD

**Issue by erikprice** [alaisi/postgres.async#4]
My database table has a column of some custom type defined with `CREATE TYPE … AS ENUM`. When `postgres.async` attempts to deserialize a value of this type, the `from-pg-value` multimethod is passed a `com.github.pgasync.impl.Oid.UNSPECIFIED` to dispatch on. But to me, this implies that all such custom types will be passed the `UNSPECIFIED` enum, so is there some way in which to disambiguate which custom type the value represents?

**Comment by alaisi** [comment]
Hi,

as far as I understand, oid values for enums are generated when the type is created. The protocol only sends the numeric oid (found in ```pg_enum```), which the Java library then maps to ```UNSPECIFIED```. If all your custom types are enums, you could get away with something like this:

```clojure
(defmethod from-pg-value com.github.pgasync.impl.Oid/UNSPECIFIED [_ value] 
    (-> value (String. "UTF-8") (keyword)))
```
This of course creates a keyword instead of Java enum and breaks down with other custom types.

So currently there is no way to disambiguate the types. Ideas and pull requests are welcome!

**Comment by erikprice** [comment]
Thanks @alaisi, this is helpful info. I think converting all custom types (`UNSPECIFIED` Oids) to strings will suffice in my case (in fact I came up with nearly that exact same code, sans the `keyword` call). If it doesn't, I will give some thought to how we could leverage the `enumtypid` in the `pg_enum` table to determine which custom type is being deserialized.
